# These are supported funding model platforms

github: [adi-sg]
# patreon: # Replace with a single Patreon username
# ko_fi: # Replace with a single Ko-fi username
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
